name: Releases
on: 
  push:
    tags:
      - "*"
jobs:
    release:
        name: ${{ matrix.platforms.friendly_name }} Qt ${{ matrix.qt_version.qt_ver }} Release
        runs-on: ${{ matrix.platforms.os }}
        permissions:
            contents: write
        strategy:
          max-parallel: 1
          matrix:
              qt_version:
                - { qt_ver: 6.7.0}
              platforms:
                - { os: windows-latest, generator: "NMake Makefiles", debug_postfix: d, compression: ZIP, friendly_name: MSVC }
        steps:
          - name: Install Qt
            if: ${{ matrix.platforms.friendly_name != 'MinGW' }}
            uses: jurplel/install-qt-action@v3
            with:
              version: ${{ matrix.qt_version.qt_ver }}
          - name: Git Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Create Build Directory
            run: |
              mkdir build
          - name: Set up MSVC environment
            if: ${{ matrix.platforms.friendly_name == 'MSVC' }}
            uses: ilammy/msvc-dev-cmd@v1
          - name: Build Release
            run: |
              cd build
              cmake -G"${{ matrix.platforms.generator }}" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX="../installed" ../
              cmake --build .
          - name: Create Package
            run: |
              cd build
              cpack -G ${{ matrix.platforms.compression }} --config ../cmake/modules/package.cmake
          - name: Publish Package to Release
            uses: ncipollo/release-action@v1
            with:
              artifacts: "build/TestBudget*.*"
              token: ${{ secrets.GITHUB_TOKEN }}
              allowUpdates: true
              artifactErrorsFailBuild: true
              draft: true
    removedraft:
        name: Remove Draft from Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: release
        steps:
          - name: Publish Release
            uses: ncipollo/release-action@v1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              allowUpdates: true
              draft: false